import sushi from "./assets/sushi.jpg";

export const PRODUCTOS = [
  {
    id: 1,
    nombre: "Producto 1",
    precio: 15000,
    categoria: "rolls",
    img: sushi,
  },
  {
    id: 2,
    nombre: "Producto 2",
    precio: 20000,
    categoria: "ceviches",
    img: sushi,
  },
  {
    id: 3,
    nombre: "Producto 3",
    precio: 25000,
    categoria: "burgers",
    img: sushi,
  },
  {
    id: 5,
    nombre: "Producto 4",
    precio: 30000,
    categoria: "rolls",
    img: sushi,
  },
  {
    id: 6,
    nombre: "Producto 1",
    precio: 15000,
    categoria: "rolls",
    img: sushi,
  },
  {
    id: 7,
    nombre: "Producto 2",
    precio: 20000,
    categoria: "ceviches",
    img: sushi,
  },
  {
    id: 8,
    nombre: "Producto 3",
    precio: 25000,
    categoria: "burgers",
    img: sushi,
  },
  {
    id: 9,
    nombre: "Producto 4",
    precio: 30000,
    categoria: "rolls",
    img: sushi,
  },
  {
    id: 10,
    nombre: "Producto 1",
    precio: 15000,
    categoria: "rolls",
    img: sushi,
  },
  {
    id: 11,
    nombre: "Producto 2",
    precio: 20000,
    categoria: "ceviches",
    img: sushi,
  },
  {
    id: 12,
    nombre: "Producto 3",
    precio: 25000,
    categoria: "burgers",
    img: sushi,
  },
  {
    id: 13,
    nombre: "Producto 4",
    precio: 30000,
    categoria: "rolls",
    img: sushi,
  },
  {
    id: 14,
    nombre: "Producto 1",
    precio: 15000,
    categoria: "rolls",
    img: sushi,
  },
  {
    id: 15,
    nombre: "Producto 2",
    precio: 20000,
    categoria: "ceviches",
    img: sushi,
  },
  {
    id: 16,
    nombre: "Producto 3",
    precio: 25000,
    categoria: "burgers",
    img: sushi,
  },
  {
    id: 17,
    nombre: "Producto 4",
    precio: 30000,
    categoria: "rolls",
    img: sushi,
  },
];
export const CATEGORIAS = {
  TODO: "todo",
  ROLLS: "rolls",
  CEVICHES: "ceviches",
  BURGERS: "burgers",
  TABLAS: "tablas",
  COMBOS: "combos",
  PREMIUM: "premium",
};