import sushi from "./assets/sushi.jpg";
import burger from "./assets/burger.jpg";
import ceviche from "./assets/ceviche.jpg";
import premium from "./assets/premium.jpg";
import tabla from "./assets/tabla.jpg";
export const PRODUCTOS = [
  {
    id: 1,
    nombre: "Producto 1",
    precio: 15000,
    categoria: "rolls",
    img: sushi,
  },
  {
    id: 2,
    nombre: "Producto 2",
    precio: 20000,
    categoria: "ceviches",
    img: ceviche,
  },
  {
    id: 3,
    nombre: "Producto 3",
    precio: 25000,
    categoria: "burgers",
    img: burger,
  },
  {
    id: 4,
    nombre: "Producto 4",
    precio: 30000,
    categoria: "rolls",
    img: sushi,
  },
  {
    id: 5,
    nombre: "Producto 5",
    precio: 15000,
    categoria: "rolls",
    img: sushi,
  },
  {
    id: 6,
    nombre: "Producto 6",
    precio: 20000,
    categoria: "ceviches",
    img: ceviche,
  },
  {
    id: 7,
    nombre: "Producto 7",
    precio: 25000,
    categoria: "burgers",
    img: burger,
  },
  {
    id: 8,
    nombre: "Producto 8",
    precio: 30000,
    categoria: "rolls",
    img: sushi,
  },
  {
    id: 9,
    nombre: "Producto 9",
    precio: 15000,
    categoria: "rolls",
    img: sushi,
  },
  {
    id: 10,
    nombre: "Producto 10",
    precio: 20000,
    categoria: "ceviches",
    img: ceviche,
  },
  {
    id: 11,
    nombre: "Producto 11",
    precio: 25000,
    categoria: "burgers",
    img: burger,
  },
  {
    id: 12,
    nombre: "Producto 12",
    precio: 30000,
    categoria: "rolls",
    img: sushi,
  },
  {
    id: 13,
    nombre: "Producto 13",
    precio: 15000,
    categoria: "rolls",
    img: sushi,
  },
  {
    id: 14,
    nombre: "Producto 14",
    precio: 20000,
    categoria: "ceviches",
    img: ceviche,
  },
  {
    id: 15,
    nombre: "Producto 15",
    precio: 25000,
    categoria: "burgers",
    img: burger,
  },
  {
    id: 16,
    nombre: "Producto 16",
    precio: 30000,
    categoria: "rolls",
    img: sushi,
  },
  {
    id: 17,
    nombre: "Producto 17",
    precio: 23500,
    categoria: "premium",
    img: premium,
  },
  {
    id: 18,
    nombre: "Producto 18",
    precio: 25000,
    categoria: "premium",
    img: premium,
  },
  {
    id: 19,
    nombre: "Producto 19",
    precio: 27500,
    categoria: "premium",
    img: premium,
  },
  {
    id: 20,
    nombre: "Producto 20",
    precio: 23500,
    categoria: "tablas",
    img: tabla,
  },
  {
    id: 21,
    nombre: "Producto 21",
    precio: 25000,
    categoria: "tablas",
    img: tabla,
  },
  {
    id: 22,
    nombre: "Producto 22",
    precio: 27500,
    categoria: "tablas",
    img: tabla,
  },
];
export const CATEGORIAS = {
  TODO: "todo",
  ROLLS: "rolls",
  CEVICHES: "ceviches",
  BURGERS: "burgers",
  TABLAS: "tablas",
  PREMIUM: "premium",
};